<?php


class Test_Wpc_Scripts extends WP_UnitTestCase
{
		var $wpc_scripts;

	public function setUp():  void
	{
		parent::setUp(); // TODO: Change the autogenerated stub

		$this->wpc_scripts = new \WPClawler\Wp_Crawler();


	}

	public function test_add_sos_scripts()
	{

		$this->assertFalse(wp_style_is('wpc_css', 'enqueued'));
		$this->assertFalse(wp_script_is('wpc_script', 'enqueued'));

		$this->wpc_scripts->wpc_add_scripts();

		$this->assertTrue(wp_style_is('wpc_css', 'registered'));
		$this->assertTrue(wp_script_is('wpc_script', 'registered'));


		$this->assertTrue(wp_style_is('wpc_css', 'enqueued'));
		$this->assertTrue(wp_script_is('wpc_script', 'enqueued'));

	}


}
